# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
